### ISSUE TITLE
NameError: name 'culture' is not defined

### ISSUE THREAD

**Issue by deolu007** [aalireza/SimpleAudioIndexer#6]
This was my initial command; indexer.index_audio(basename=culture.wav)
and the output
NameError: name 'culture' is not defined

**Comment by aalireza** [comment]
As you can see in [the manual](https://simpleaudioindexer.readthedocs.io/reference/#SimpleAudioIndexer.SimpleAudioIndexer.index_audio), `basename` expects a string which means for `basename=culture.wav` doesn't make sense unless you have previously defined an object `culture` whose attribute `wav` refers to a string. If that's the case, please comment, but if not, you should have `basename="culture.wav"` and I'd presume it'd work as expected.

**Comment by deolu007** [comment]
I made the correction,  indexer.index_audio(basename=**"culture.wav"**)

I'm getting a new error

ValueError: could not convert string to float: do

**Comment by aalireza** [comment]
The error is mentioned in #5 as well as here. I'll respond there.
